### ISSUE TITLE
Application opens an empty "NoName" window on startup

### ISSUE THREAD

**Issue by yurivict** [brummer10/XUiDesigner#10]
![image](https://user-images.githubusercontent.com/271906/178044192-bd48bccc-c0c2-4f45-b1d7-ac5c2d2e32a9.png)

**Comment by brummer10** [comment]
Yes, that's the "Editor" window. You could add the controls by select the type in the combobox on the left top corner and then do a right click on the empty window. 
You could give the name (Project name will be the Window name as well) beside other settings in the Settings window, the first button on the right corner on base will pop it up. You'll see there that a empty project simple has the name "NoName".
Or, when you select a LV2 plugin from the combobox in the middle, the window name will change according the selected plug.
Same when you load a faust file.

**Comment by yurivict** [comment]
Ok. Thank you for the explanation.
