### ISSUE TITLE
Problems with reloaded Json files

### ISSUE THREAD

**Issue by RedeyeAudio** [brummer10/XUiDesigner#20]
Each time I reload the value of the overall height of plugin decreases by 1 .

Double quote around the add_lv2_vslider and add_lv2_hslider types which then generates wrong code.

 "IS_VSLIDER" : [
    {
      "Type" : ""add_lv2_vslider"",

gives
 ui->widget[14] = "add_lv2_vslider" (ui->widget[14], ui->elem[7], 16, "OutdB", ui, 60,  20, 28 * scale, 160 * scale);

in generated code.
It is line 380 and 385 in XUiReadJson.c file ....

**Comment by brummer10** [comment]
Hi Steve
Thanks for reporting the issue. 
I've pushed a fix for it now to the repository. 
regards
hermann
