### ISSUE TITLE
Build failure on Fedora

### ISSUE THREAD

**Issue by ycollet** [brummer10/XUiDesigner#21]
While trying to build XUIDesigner on Fedora, I met a compilation error related to a wrongly formatted config.h:
```
./config.h:1:15: warning: extra tokens at end of #ifdef directive
    1 | #ifdef USE_LD \n#undef USE_LD \n#endif
      |               ^
./config.h:1: error: unterminated #ifdef
    1 | #ifdef USE_LD \n#undef USE_LD \n#endif
      | 
make[2]: *** [Makefile:168: b64_encode.o] Error 1
```

**Comment by brummer10** [comment]
what shell do you use? Usually the \n token will be interpreted as new line ( and not printed as "\n" by the echo command writing the config.h file.

**Comment by ycollet** [comment]
I use bash.

**Comment by ycollet** [comment]
I think the echo command needs the "-e" parameter to interpret all backslashed characters.

**Comment by ycollet** [comment]
```
$ echo "test \n"
test \n
```
```
$ echo -e "test \n"
test 

```

**Comment by brummer10** [comment]
Using bash here as well.
echo -e behave un consistent across  versions, hence I decided for plain echo, but that seems to be affected from versions differences as well. 
I guess I'll simply split it into 3 echos to ensure it works across versions.
Thanks for reporting, I'll fix it.

**Comment by ycollet** [comment]
Thanks for all the work you make !

**Comment by brummer10** [comment]
It's done now. Latest git version should build fine now regardless the echo version in use.
greets
hermann

**Comment by ycollet** [comment]
Build fine now. I close the ticket ! 
Thanks !
