### ISSUE TITLE
Github Action fails quickly when using drag and drop faust .dsp file

### ISSUE THREAD

**Issue by Schmitty2005** [brummer10/XUiDesigner#25]
When creating Plug In bundle using faust .dsp file (drag and drop), saving the project, pushing to github, the workflow fails very early.  Attached are the logs.

I do not know if this is an operator error, or a problem with XUiDesigner.  I do not understand Github Actions very well.

Source, Win, and Linux build fails.

All projects build on local machine. Ubuntu 24.04 LTS.   Prior to XUiDesigner updated, at least the source compiled on github.

Attached are the logs.
[logs_27305731821.zip](https://github.com/user-attachments/files/16651271/logs_27305731821.zip)

**Comment by Schmitty2005** [comment]
Drag and Drop Faust DSP still not working after previous fixes : 

Fails on the distrho makefile action : 

`  sudo rm /etc/apt/sources.list.d/*.list
  sudo apt-get update -qq
  sudo apt-get purge -yqq git-man libclang* libgbm* libllvm* libmono* libnginx* moby* mono* nginx* perl php* libgdiplus libpcre2-posix3 libselinux1-dev libzip4
  sudo apt-get install -yqq --allow-downgrades autoconf/focal automake/focal build-essential/focal git/focal libgd3/focal libglib2.0-0/focal libglib2.0-dev/focal libpcre2-8-0/focal libpcre2-16-0/focal libpcre2-32-0/focal libpcre2-posix2/focal pkg-config/focal
  sudo apt-get clean
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    PAWPAW_SKIP_LV2: 0
    DEBIAN_FRONTEND: noninteractive
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    LIBGL_ALWAYS_SOFTWARE: true
    PAWPAW_CACHE_VERSION: 8
    PAWPAW_COMMIT_HASH: 80607a764da0b5a6b2daa4d5dd165beafa0535bc
    PAWPAW_SKIP_GLIB: 1
    UBUNTU_CODENAME: focal
    UBUNTU_VERSION: 20.04
E: Unable to locate package monospace
E: Unable to locate package monospace.json
E: Couldn't find any package by glob 'monospace.json'
E: Couldn't find any package by regex 'monospace.json'
Error: Process completed with exit code 100.
`
[https://github.com/Schmitty2005/monospace_ui](url)

Local builds work without issue. 

Suggestions ?

**Comment by brummer10** [comment]
mm, could you try to rename the repository from monospace_ui to monospace and retrigger a build please.

**Comment by Schmitty2005** [comment]
I created a new repo, but renamed monospace_ui directory to monospace, then pushed. Issue remains.

[https://github.com/Schmitty2005/monospace](url)

**Comment by brummer10** [comment]
I've currently no idea what goes wrong. And unfortunately I run completely out of time. I hope that I could have a look at it next week, but can't promise.
On thing I noticed is that build.yml still using 
`actions/checkout@v3`
it should be 
`actions/checkout@v4`
instead now. However, I don't believe that that will fix the issue.

**Comment by Schmitty2005** [comment]
This may help during troubleshooting :  If I recall correctly, this commit (https://github.com/brummer10/XUiDesigner/commit/52b85db1abe021e131c3f671571a98a0b7c3e431) would at least build the GH action source correctly, but fail on the linux and win builds.

**Comment by brummer10** [comment]
I did a quick test and it worked as expected here:
https://github.com/brummer10/Marshall_MG10

The only difference I could see is that I using Camel case  name for the faust file (which makes all generated files Camel case) instead lower case names like in your repository. Still I've no idea if and why that should matter.

**Comment by brummer10** [comment]
I did a other test with lowercase names and it works as well. 
https://github.com/brummer10/tone
I've now pushed a update to XUidesigner to use actions/checkout@v4 in the generated build.yml file.

**Comment by Schmitty2005** [comment]
Thank you for checking into this.  I copied the chorus.dsp from the guitarix source, made a quick UI with XUiDesigner, and pushed to github.  It is currently building and will likely work. 

It seems my .dsp file must be the cause.  I will see what I can do to narrow down what is causing it, but my first guess is that I do have the declared name in the faust.dsp file different from the filename that it is saved as.    I was renaming the .dsp file, but not changing the declaration in the faust code.     Likely a user error on my part.

**Comment by Schmitty2005** [comment]
Thank you!
