### ISSUE TITLE
Intermediary save format

### ISSUE THREAD

**Issue by falkTX** [brummer10/XUiDesigner#4]
Would be great to be possible to save the created UI in an intermediary format for later editing.
Right now XUiDesigner is all or nothing - we export the UI as LV2 bundle or we don't.
If we want to edit that UI further we need to redo them all again.

An intermediary format, whatever that may be, would allow to keep working on the GUI over a period of several days, tweaking stuff along the way.

**Comment by brummer10** [comment]
So interim save format is implemented now. Ui description will be saved in json format file. 
Means, I close this issue now.
