### ISSUE TITLE
Makefile doesn't respect PREFIX

### ISSUE THREAD

**Issue by yurivict** [brummer10/XUiDesigner#8]
This [line](https://github.com/brummer10/XUiDesigner/blob/main/XUiDesigner/Makefile#L113) and the next line install into ```/usr/share``` instead of ```$(PREFIX)/share```.

**Comment by brummer10** [comment]
That is intentional. XUiDesigner needs to know were those files been installed, as we need them to copy to a saved LV2 Bundle.

**Comment by yurivict** [comment]
```/usr/share/``` doesn't exist, ```/usr``` should be replaced with ```$PREFIX```.

**Comment by brummer10** [comment]
Okay. I've fixed that now within the last commit. 

regards
hermann

**Comment by yurivict** [comment]
Thanks!
